DECLARE @NAMESURNAME AS VARCHAR(50)=''
DECLARE @AGE AS INT
DECLARE @EMAIL AS VARCHAR(100)=''
DECLARE @MSG AS VARCHAR(500) 

--SELECT *,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) FROM USERS
--WHERE DAY (BIRTHDATE) = 07 AND MONTH (BIRTHDATE) = 03

DECLARE CRS CURSOR FOR
	SELECT NAMESURNAME,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AS AGE,EMAIL
		FROM USERS
	WHERE DAY (BIRTHDATE) = 11 AND MONTH (BIRTHDATE) = 3
OPEN CRS
FETCH NEXT FROM CRS INTO @NAMESURNAME,@AGE,@EMAIL

WHILE @@FETCH_STATUS=0
BEGIN
	SET @MSG = 'Sayýn '+@NAMESURNAME+',Doðum gününüz kutlu olsun.' +CONVERT(VARCHAR,@AGE)+'. Yaþýnýzý kutlar, nice mutlu yýllar dileriz.'

EXEC msdb.dbo.sp_send_dbmail 
    @profile_name='DODO',
    @recipients = @EMAIL,
    @subject='MUTLU YILLAR',
    @body = @MSG

FETCH NEXT FROM CRS INTO @NAMESURNAME,@AGE,@EMAIL
END
CLOSE CRS
DEALLOCATE CRS




